### ISSUE TITLE
Add laravel-dashboard

### ISSUE THREAD

**Issue by wotta** [wotta/dashboard#2]
See more details at https://spatie.be/docs/laravel-dashboard/v2/installation-setup

**Comment by JunaidJaved248** [comment]
@wotta Should I contribute in it? If still this issue not resolved?

**Comment by wotta** [comment]
JunaidJaved248 the spatie dashboard is already installed. But if you want you may create a pr do the weather tile from spatie :)

I will work more issues out tomorrow since I want to give othera the ability to be able to contribute ( even if it is for hacktober :) )

**Comment by JunaidJaved248** [comment]
OK Right!! Mention me when you found more issues, I will resolve those issues.
